/// Flutter icons MyIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons
///      fonts:
///       - asset: fonts/MyIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyIcons {
  MyIcons._();

  static const _kFontFam = 'MyIcons';
  static const _kFontPkg = null;

  static const IconData bottle = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cow = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData date = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dose = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData employee = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exit = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData farm = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData farms = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData history = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData password = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData price = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
