/// Flutter icons MyIcons2
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIcons2
///      fonts:
///       - asset: fonts/MyIcons2.ttf
///
///
///
import 'package:flutter/widgets.dart';

class MyIcons2 {
  MyIcons2._();

  static const _kFontFam = 'MyIcons2';
  static const _kFontPkg = null;

  static const IconData caneca4 =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
